# Generated by Django 4.1 on 2022-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0002_alter_comment_account_alter_comment_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='picture',
            new_name='cover_picture',
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
