# Generated by Django 4.1 on 2022-10-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0003_rename_picture_activity_cover_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='description',
            new_name='content',
        ),
    ]
