# Generated by Django 4.1 on 2022-10-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0005_migrate_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_activity.comment'),
        ),
        migrations.AlterField(
            model_name='adoptrequest',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
    ]
