# Generated by Django 4.1 on 2022-10-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0005_migrate_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adoptintroductactivity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adoptrequest',
            name='is_active',
        ),
    ]
