# Generated by Django 4.1 on 2022-10-16 08:15

from django.db import migrations

from api_activity.static.activity import ActivityTypeData


def init_data_activity_type(apps, schema_editor):
    activity_type_model = apps.get_model("api_activity", "ActivityType")
    activity_type_group_model = apps.get_model("api_activity", "ActivityTypeGroup")
    activity_group = [activity_type_group_model(id=group['id'], name=group['name']) for group in
                      ActivityTypeData.activity_type_group]
    activity_type_group_model.objects.bulk_create(activity_group)

    activity_type = [activity_type_model(id=activity_type['id'], name=activity_type['name'],
                                         activity_type_group=activity_type_group_model.objects.get(id=activity_type['activity_type_group']))
                     for activity_type in ActivityTypeData.activity_type]

    activity_type_model.objects.bulk_create(activity_type)


class Migration(migrations.Migration):

    dependencies = [
        ('api_activity', '0006_remove_activity_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(init_data_activity_type, migrations.RunPython.noop)
    ]
