# Generated by Django 4.1 on 2022-09-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_migrate_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
