# Generated by Django 4.1 on 2022-09-27 12:54

import base.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_profile_personal_email_alter_profile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vip_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=base.models.fields.TinyIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3),
        ),
    ]
