# Generated by Django 4.1 on 2022-10-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_profile_is_vip_donor_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
    ]
