# Generated by Django 4.1 on 2022-09-11 06:59
from api_user.statics import RoleData, AccountData, ProfileData
from django.db import migrations
from django.contrib.auth.hashers import make_password
import os
from dotenv import load_dotenv

load_dotenv()


def init_employee_data(apps, schema_editor):
    account_model = apps.get_model("api_user", "Account")
    role_model = apps.get_model("api_user", "Role")
    profile_model = apps.get_model("api_user", "Profile")
    employee_role = role_model.objects.filter(
        id=RoleData.EMPLOYEE.value.get('id')).first()
    employees = []
    accounts = []
    through_objs = []

    for account, profile in zip(AccountData.accounts, ProfileData.profiles):
        accounts.append(account_model(
            id=account['id'],
            email=account['email'],
            password=make_password(os.getenv("DEFAULT_EMPLOYEE_PASSWORD"), salt=os.getenv("SECRET_KEY")),
        ))
        employees.append(profile_model(
            name=profile['name'],
            gender=profile['gender'],
            account_id=account['id'],
            occupation=profile['occupation'],
            personal_email=account['email'],
        ))
        through_objs.append(
            account_model.roles.through(
                account_id=account['id'],
                role_id=employee_role.id,
            ),
        )
    account_model.objects.bulk_create(accounts)
    account_model.roles.through.objects.bulk_create(through_objs)
    profile_model.objects.bulk_create(employees)


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_remove_account_is_active_remove_profile_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(init_employee_data, migrations.RunPython.noop),
    ]
