# Generated by Django 4.1 on 2022-11-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0007_migrate_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='levels',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
