# Generated by Django 4.1 on 2022-10-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_statistic', '0002_remove_donor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donor_amount',
        ),
        migrations.AddField(
            model_name='donor',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
