# Generated by Django 4.1 on 2022-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_statistic', '0003_remove_donor_donor_amount_donor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='note',
            field=models.CharField(default='', max_length=565),
        ),
    ]
