# Generated by Django 4.1 on 2022-09-21 14:44

import base.models.fields
import datetime
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0004_profile_personal_email_alter_profile_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', base.models.fields.TinyIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('personal_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('join_date', models.DateField(blank=True, default=datetime.datetime(2022, 9, 21, 21, 44, 21, 134169), null=True)),
                ('adopt_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Unadopted', max_length=10)),
                ('adopter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopter', to='api_user.profile')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presenter', to='api_user.profile')),
            ],
            options={
                'db_table': 'children',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
