# Generated by Django 4.1 on 2022-10-01 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_children', '0004_alter_children_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='join_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
