# Generated by Django 4.1 on 2022-09-27 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_children', '0004_alter_children_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 28, 0, 34, 8, 152401), null=True),
        ),
    ]
