# Generated by Django 4.1 on 2022-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_children', '0005_alter_children_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='is_active',
        ),
        migrations.AddField(
            model_name='children',
            name='identifier',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
